# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_auto_pc_0/axis_morph_bd_auto_pc_0.xci
# IP: The module: 'axis_morph_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_auto_pc_0/axis_morph_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_morph_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_auto_pc_0/axis_morph_bd_auto_pc_0.xci
# IP: The module: 'axis_morph_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_auto_pc_0/axis_morph_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_morph_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
