# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/axis_morph_clock.xdc

# XDC: imports/sysgen/axis_morph.xdc

# Block Designs: bd/axis_morph_bd/axis_morph_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_bd || ORIG_REF_NAME==axis_morph_bd} -quiet] -quiet

# IP: bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_bd_axis_morph_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_bd_axis_morph_1_0 || ORIG_REF_NAME==axis_morph_bd_axis_morph_1_0} -quiet] -quiet

# IP: bd/axis_morph_bd/ip/axis_morph_bd_processing_system_1_0/axis_morph_bd_processing_system_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_bd_processing_system_1_0 || ORIG_REF_NAME==axis_morph_bd_processing_system_1_0} -quiet] -quiet

# IP: bd/axis_morph_bd/ip/axis_morph_bd_processing_system_1_axi_periph_0/axis_morph_bd_processing_system_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_bd_processing_system_1_axi_periph_0 || ORIG_REF_NAME==axis_morph_bd_processing_system_1_axi_periph_0} -quiet] -quiet

# IP: bd/axis_morph_bd/ip/axis_morph_bd_rst_processing_system_1_50M_0/axis_morph_bd_rst_processing_system_1_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_bd_rst_processing_system_1_50M_0 || ORIG_REF_NAME==axis_morph_bd_rst_processing_system_1_50M_0} -quiet] -quiet

# IP: bd/axis_morph_bd/ip/axis_morph_bd_auto_pc_0/axis_morph_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_bd_auto_pc_0 || ORIG_REF_NAME==axis_morph_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/axis_morph_bd/axis_morph_bd_ooc.xdc
