# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Xil_proj/315/proj/DIY/imp/imp.runs/synth_1/d1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xil_proj/315/proj/DIY/imp/imp.cache/wt [current_project]
set_property parent.project_path C:/Xil_proj/315/proj/DIY/imp/imp.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Xil_proj/315/proj/DIY/netlist/ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Xil_proj/315/proj/DIY/imp/imp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/hdl/d1_wrapper.v
add_files C:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/d1.bd
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_axis_morph_0_0/axis_morph_fifo_generator_i0/axis_morph_fifo_generator_i0.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_axis_morph_0_0/axis_morph_fifo_generator_i1/axis_morph_fifo_generator_i1.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_axis_morph_0_0/constrs/axis_morph.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_processing_system7_0_0/d1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_axi_dma_0_0/d1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_axi_dma_0_0/d1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_axi_dma_0_0/d1_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_proc_sys_reset_0_0/d1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_proc_sys_reset_0_0/d1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_proc_sys_reset_0_0/d1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_xbar_0/d1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/ip/d1_auto_pc_0/d1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Xil_proj/315/proj/DIY/imp/imp.srcs/sources_1/bd/d1/d1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Xil_proj/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc}}
set_property used_in_implementation false [get_files {{C:/Xil_proj/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top d1_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef d1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file d1_wrapper_utilization_synth.rpt -pb d1_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
