# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xil_proj/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/d1/d1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==d1 || ORIG_REF_NAME==d1} -quiet] -quiet

# IP: bd/d1/ip/d1_axis_morph_0_0/d1_axis_morph_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==d1_axis_morph_0_0 || ORIG_REF_NAME==d1_axis_morph_0_0} -quiet] -quiet

# IP: bd/d1/ip/d1_processing_system7_0_0/d1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==d1_processing_system7_0_0 || ORIG_REF_NAME==d1_processing_system7_0_0} -quiet] -quiet

# IP: bd/d1/ip/d1_axi_dma_0_0/d1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==d1_axi_dma_0_0 || ORIG_REF_NAME==d1_axi_dma_0_0} -quiet] -quiet

# IP: bd/d1/ip/d1_axi_interconnect_0_0/d1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==d1_axi_interconnect_0_0 || ORIG_REF_NAME==d1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/d1/ip/d1_proc_sys_reset_0_0/d1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==d1_proc_sys_reset_0_0 || ORIG_REF_NAME==d1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/d1/ip/d1_xbar_0/d1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==d1_xbar_0 || ORIG_REF_NAME==d1_xbar_0} -quiet] -quiet

# IP: bd/d1/ip/d1_auto_pc_0/d1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==d1_auto_pc_0 || ORIG_REF_NAME==d1_auto_pc_0} -quiet] -quiet

# XDC: bd/d1/d1_ooc.xdc
