# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_bd_axis_morph_1_0.xci
# IP: The module: 'axis_morph_bd_axis_morph_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i0/axis_morph_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i0 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i1/axis_morph_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i1 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i2/axis_morph_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i2 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i3/axis_morph_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i3 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i4/axis_morph_c_addsub_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i4 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_counter_binary_v12_0_i0/axis_morph_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==axis_morph_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_counter_binary_v12_0_i1/axis_morph_c_counter_binary_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==axis_morph_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_fifo_generator_i0/axis_morph_fifo_generator_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_fifo_generator_i0 || ORIG_REF_NAME==axis_morph_fifo_generator_i0} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_fifo_generator_i1/axis_morph_fifo_generator_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_fifo_generator_i1 || ORIG_REF_NAME==axis_morph_fifo_generator_i1} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i0/axis_morph_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i0 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i1/axis_morph_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i1 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i2/axis_morph_mult_gen_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i2 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i3/axis_morph_mult_gen_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i3 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i4/axis_morph_mult_gen_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i4 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i4} -quiet] -quiet

# XDC: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_fifo_generator_i0/axis_morph_fifo_generator_i0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_morph_fifo_generator_i0 || ORIG_REF_NAME==axis_morph_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_fifo_generator_i1/axis_morph_fifo_generator_i1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_morph_fifo_generator_i1 || ORIG_REF_NAME==axis_morph_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/constrs/axis_morph.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_morph_bd_axis_morph_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_bd_axis_morph_1_0.xci
# IP: The module: 'axis_morph_bd_axis_morph_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i0/axis_morph_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i0 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i1/axis_morph_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i1 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i2/axis_morph_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i2 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i3/axis_morph_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i3 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_addsub_v12_0_i4/axis_morph_c_addsub_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_addsub_v12_0_i4 || ORIG_REF_NAME==axis_morph_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_counter_binary_v12_0_i0/axis_morph_c_counter_binary_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==axis_morph_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_c_counter_binary_v12_0_i1/axis_morph_c_counter_binary_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==axis_morph_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_fifo_generator_i0/axis_morph_fifo_generator_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_fifo_generator_i0 || ORIG_REF_NAME==axis_morph_fifo_generator_i0} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_fifo_generator_i1/axis_morph_fifo_generator_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_fifo_generator_i1 || ORIG_REF_NAME==axis_morph_fifo_generator_i1} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i0/axis_morph_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i0 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i1/axis_morph_mult_gen_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i1 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i2/axis_morph_mult_gen_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i2 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i3/axis_morph_mult_gen_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i3 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_mult_gen_v12_0_i4/axis_morph_mult_gen_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_morph_mult_gen_v12_0_i4 || ORIG_REF_NAME==axis_morph_mult_gen_v12_0_i4} -quiet] -quiet

# XDC: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_fifo_generator_i0/axis_morph_fifo_generator_i0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_morph_fifo_generator_i0 || ORIG_REF_NAME==axis_morph_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/axis_morph_fifo_generator_i1/axis_morph_fifo_generator_i1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_morph_fifo_generator_i1 || ORIG_REF_NAME==axis_morph_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xil_proj/315/proj/DIY/netlist/ip_catalog/axis_morph.srcs/sources_1/bd/axis_morph_bd/ip/axis_morph_bd_axis_morph_1_0/constrs/axis_morph.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_morph_bd_axis_morph_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
