# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/315/uwu2/fun/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/design_1_axi_stream_morphing_0_0.xci
# IP: The module: 'design_1_axi_stream_morphing_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i0/axi_stream_morphing_backup2_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i0} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i1/axi_stream_morphing_backup2_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i1 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i1} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i2/axi_stream_morphing_backup2_c_addsub_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i2 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i2} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i3/axi_stream_morphing_backup2_c_addsub_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i3 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i3} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i4/axi_stream_morphing_backup2_c_addsub_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i4 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i4} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_counter_binary_v12_0_i0/axi_stream_morphing_backup2_c_counter_binary_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_fifo_generator_i0/axi_stream_morphing_backup2_fifo_generator_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_fifo_generator_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_fifo_generator_i0} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_fifo_generator_i1/axi_stream_morphing_backup2_fifo_generator_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_fifo_generator_i1 || ORIG_REF_NAME==axi_stream_morphing_backup2_fifo_generator_i1} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_mult_gen_v12_0_i0/axi_stream_morphing_backup2_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i0} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_mult_gen_v12_0_i1/axi_stream_morphing_backup2_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i1 || ORIG_REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i1} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_mult_gen_v12_0_i2/axi_stream_morphing_backup2_mult_gen_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i2 || ORIG_REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i2} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_mult_gen_v12_0_i3/axi_stream_morphing_backup2_mult_gen_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i3 || ORIG_REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i3} -quiet] -quiet

# XDC: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_fifo_generator_i0/axi_stream_morphing_backup2_fifo_generator_i0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_fifo_generator_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_fifo_generator_i1/axi_stream_morphing_backup2_fifo_generator_i1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_fifo_generator_i1 || ORIG_REF_NAME==axi_stream_morphing_backup2_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/constrs/axi_stream_morphing_backup2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_stream_morphing_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/design_1_axi_stream_morphing_0_0.xci
# IP: The module: 'design_1_axi_stream_morphing_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i0/axi_stream_morphing_backup2_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i0} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i1/axi_stream_morphing_backup2_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i1 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i1} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i2/axi_stream_morphing_backup2_c_addsub_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i2 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i2} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i3/axi_stream_morphing_backup2_c_addsub_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i3 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i3} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_addsub_v12_0_i4/axi_stream_morphing_backup2_c_addsub_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i4 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_addsub_v12_0_i4} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_c_counter_binary_v12_0_i0/axi_stream_morphing_backup2_c_counter_binary_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_fifo_generator_i0/axi_stream_morphing_backup2_fifo_generator_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_fifo_generator_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_fifo_generator_i0} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_fifo_generator_i1/axi_stream_morphing_backup2_fifo_generator_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_fifo_generator_i1 || ORIG_REF_NAME==axi_stream_morphing_backup2_fifo_generator_i1} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_mult_gen_v12_0_i0/axi_stream_morphing_backup2_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i0} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_mult_gen_v12_0_i1/axi_stream_morphing_backup2_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i1 || ORIG_REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i1} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_mult_gen_v12_0_i2/axi_stream_morphing_backup2_mult_gen_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i2 || ORIG_REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i2} -quiet] -quiet

# IP: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_mult_gen_v12_0_i3/axi_stream_morphing_backup2_mult_gen_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i3 || ORIG_REF_NAME==axi_stream_morphing_backup2_mult_gen_v12_0_i3} -quiet] -quiet

# XDC: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_fifo_generator_i0/axi_stream_morphing_backup2_fifo_generator_i0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_fifo_generator_i0 || ORIG_REF_NAME==axi_stream_morphing_backup2_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/axi_stream_morphing_backup2_fifo_generator_i1/axi_stream_morphing_backup2_fifo_generator_i1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_stream_morphing_backup2_fifo_generator_i1 || ORIG_REF_NAME==axi_stream_morphing_backup2_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/315/uwu2/fun/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_stream_morphing_0_0/constrs/axi_stream_morphing_backup2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_stream_morphing_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
